# Generated by Django 5.2.7 on 2026-03-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mentoravailability_mentorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialties',
            field=models.TextField(blank=True, help_text="Domaines d'expertise (ex: logement, études, emploi)"),
        ),
    ]
