# Generated by Django 5.2.7 on 2026-03-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('admin', 'Administration'), ('bank', 'Banque'), ('grocery', 'Épicerie'), ('transport', 'Transport'), ('health', 'Santé'), ('leisure', 'Loisirs'), ('other', 'Autre')], max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='universities.university')),
            ],
        ),
    ]
