# Generated by Django 5.2.7 on 2026-03-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='how_to',
            field=models.TextField(blank=True, help_text='Comment obtenir/faire (FR)'),
        ),
        migrations.AddField(
            model_name='task',
            name='how_to_en',
            field=models.TextField(blank=True, help_text='How to obtain/do (EN)'),
        ),
        migrations.AddField(
            model_name='task',
            name='locations',
            field=models.TextField(blank=True, help_text='Lieux et adresses (FR)'),
        ),
        migrations.AddField(
            model_name='task',
            name='locations_en',
            field=models.TextField(blank=True, help_text='Locations and addresses (EN)'),
        ),
        migrations.AddField(
            model_name='task',
            name='tips',
            field=models.TextField(blank=True, help_text='Conseils et astuces (FR)'),
        ),
        migrations.AddField(
            model_name='task',
            name='tips_en',
            field=models.TextField(blank=True, help_text='Tips and tricks (EN)'),
        ),
    ]
