# Generated by Django 5.2.7 on 2026-03-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_task_how_to_task_how_to_en_task_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='category',
            field=models.CharField(choices=[('admin', 'Administration'), ('university', 'Université'), ('transport', 'Transport'), ('housing', 'Logement & Installation'), ('work', "Recherche d'Emploi")], max_length=20),
        ),
    ]
