# Generated by Django 5.2.7 on 2026-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_alter_step_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='category',
            field=models.CharField(choices=[('admin', 'Administration'), ('university', 'Université'), ('transport', 'Transport'), ('housing', 'Logement & Installation'), ('work', "Recherche d'Emploi"), ('lifestyle', 'Vie au Québec')], max_length=20),
        ),
    ]
